### PR TITLE
Apply some code refactor

### PR DESCRIPTION
**Pull request by calancha**
Reduce complexity of `compile_tokens'; pacify Rubocop.
* lib/goodcheck/pattern.rb (extract_tokens):
New method extracted from `compile_tokens'.
(compile_tokens): Use it.

### CODE REVIEW

**Comment by soutaro** [comment]
I don't think this rewriting make some sense.
Could you give me more explanation than *pacify RuboCop*.

**Comment by calancha** [comment]
Sure.
Rubocop give me the following warnings about ```compile_tokens```:
Perceived complexity for compile_tokens is too high. [10/7] [Metrics/PerceivedComplexity]
Method has too many lines. [25/10] [Metrics/MethodLength]
Cyclomatic complexity for compile_tokens is too high. [10/6] [Metrics/CyclomaticComplexity]
Assignment Branch Condition size for compile_tokens is too high. [33.62/15] [Metrics/AbcSize]
Do not use empty `case` condition, instead use an `if` expression. [Style/EmptyCaseCondition]
Favor modifier `if` usage when having a single-line body. Another good alternative is the usage of control flow `&&`/`||`. [Style/IfUnlessModifier]

After the patch, all warnings are gone and we just get
a warning for the new function ```extract_tokens```:
Method has too many lines. [16/10] [Metrics/MethodLength]

In addition, it seems to me more performant, because we store the
regexps in an array, instead of recreating those regexps inside the loop.

**Comment by soutaro** [comment]
Okay.

In this case, only one thing worth considering, in my opinion, is *Favor modifier `if` ...*. So, I'm closing this without getting merged.

If you feel something is difficult to understand, feel free to open a pull request. But, *RuboCop says* is not a reason to do something in our team.

**Comment by calancha** [comment]
On Mon, 2 Jul 2018, Soutaro Matsumoto wrote:
> In this case, only one thing worth considering, in my opinion, is Favor modifier if .... So, I'm closing this without getting
> merged.
I disagree.  Code is written once and read many times.  Small improvements 
in readibility like this make more pleasant to work with code.
> If you feel something is difficult to understand, feel free to open a pull request. But, RuboCop says is not a reason to do
> something in our team.
The code looks more compact and nicer.
Rubocop is just a tool.  We might follow Rubocop or not depending on
our group policy.

**Comment by calancha** [comment]
On Mon, 2 Jul 2018, Soutaro Matsumoto wrote:

>
>       Small improvements in readibility like this make more pleasant to work with code.
> 
> Yes, totally.
> The problem is that I don't agree with the improvements you proposed improves something.
Fair enough.
Then you disagree with me and with Rubocop (507 contributors) ;-)

**Pull request closed without merging**
